name: 'My firtsh github action'

on: push
#어느 시점에서 이 깃헙 액션이 실행되는지 설정하는지. 커맨트 달떄? 푸쉬할 때? -> 이벤트 기반의 워크플로우

env: #환경변수를 만듦. 전체에서 가능, jobs 단위에서 가능, step 단위에서 가능. -> scope 단위에서 이루어진다고 보면 될듯
  WORKFLOW_LEVEL: 'THIS VALUE COMES FROM THE WORKFLOW LEVEL'

jobs: # on 시점에 jobs의 밑에 있는 것들을 쭉 실행시켜라
  first-job: #build server 중 하나
    name: 'first job'

    runs-on: ubuntu-latest #macos-latest #windows-latest

    step:
    - name: set output value
      id: first
      shell: bash
      run: |
        first_value="This is the first output value"

        echo "::set-output name=my_first_value::$first_value"

    - name: get output value
      shell: bash
      runt: |
        echo ${{ steps.firts.outputs.my_first_value }}